# Generated by Django 4.0.5 on 2022-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('updateDate', models.DateTimeField(verbose_name='Дата обновления')),
                ('type', models.SlugField(choices=[('CATEGORY', 'Категория'), ('OFFER', 'Товар')], default='CATEGORY', max_length=10)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('parentId', models.UUIDField(null=True)),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
            ],
        ),
    ]
