# Generated by Django 4.0.5 on 2022-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='updateDate',
            field=models.DateTimeField(null=True, verbose_name='Дата обновления'),
        ),
    ]
