# Generated by Django 4.0.5 on 2022-06-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_updatedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateTimeField(verbose_name='Дата обновления')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='updateDate',
        ),
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.time'),
        ),
    ]
