# Generated by Django 4.0.5 on 2022-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_parent_item_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
