# Generated by Django 4.0.5 on 2022-06-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='time',
            new_name='date',
        ),
    ]
